# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djcollect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_node_id', models.CharField(max_length=24)),
                ('trial_index', models.IntegerField()),
                ('trial_type', models.CharField(max_length=32)),
                ('time_elapsed', models.IntegerField()),
                ('timeout', models.BooleanField(default=False)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('key_press', models.PositiveSmallIntegerField()),
                ('rt', models.PositiveIntegerField()),
                ('correct', models.BooleanField()),
                ('category', models.CharField(max_length=24, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CogComSimilarityTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_node_id', models.CharField(max_length=24)),
                ('trial_index', models.IntegerField()),
                ('trial_type', models.CharField(max_length=32)),
                ('time_elapsed', models.IntegerField()),
                ('timeout', models.BooleanField(default=False)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('sim_score', models.PositiveIntegerField()),
                ('rt', models.PositiveIntegerField()),
                ('firstStim', models.CharField(max_length=24)),
                ('secondStim', models.CharField(max_length=24)),
                ('kind', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('browser', models.CharField(max_length=16, null=True)),
                ('browser_version', models.CharField(max_length=8, null=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcollect.Participation')),
                ('used_trials', models.ManyToManyField(to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_node_id', models.CharField(max_length=24)),
                ('trial_index', models.IntegerField()),
                ('trial_type', models.CharField(max_length=32)),
                ('time_elapsed', models.IntegerField()),
                ('timeout', models.BooleanField(default=False)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('sim_score', models.PositiveIntegerField()),
                ('rt', models.PositiveIntegerField()),
                ('firstStim', models.CharField(max_length=24)),
                ('secondStim', models.CharField(max_length=24)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreceive.Run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cogcomsimilaritytrial',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreceive.Run'),
        ),
        migrations.AddField(
            model_name='categorizationtrial',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreceive.Run'),
        ),
    ]
