# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djcollect', '0003_auto_20160229_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('browser', models.CharField(editable=False, max_length=16, null=True)),
                ('browser_version', models.CharField(editable=False, max_length=8, null=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcollect.Participation')),
            ],
        ),
    ]
