# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0002_cogcomhtmltrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogcomhtmltrial',
            name='difficulty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cogcomhtmltrial',
            name='ruleFound',
            field=models.BooleanField(default=False),
        ),
    ]
