# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djreceive', '0002_categorizationtrial_cogcomsimilaritytrial_similaritytrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='used_trials',
            field=models.ManyToManyField(to='contenttypes.ContentType'),
        ),
    ]
