# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0005_surveymultichoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcedchoice',
            name='first',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='forcedchoice',
            name='last',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='forcedchoice',
            name='leftRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forcedchoice',
            name='rightRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='forcedchoice',
            name='chosen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='surveylikert',
            name='responses',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveymultichoice',
            name='responses',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
