# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djreceive', '0006_auto_20161117_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='used_trials',
            field=models.ManyToManyField(related_name='containing_runs', to='contenttypes.ContentType'),
        ),
    ]
