# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0008_audiocattrial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocattrial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='audiocattrial',
            name='correct',
        ),
        migrations.AddField(
            model_name='audiocattrial',
            name='key_press',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='audiocattrial',
            name='result',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
