# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0021_xabtrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosimilaritytrial',
            name='firstStim',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='audiosimilaritytrial',
            name='secondStim',
            field=models.CharField(max_length=1024),
        ),
    ]
