# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0024_auto_20170131_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioabxtrial',
            name='result',
        ),
        migrations.AddField(
            model_name='audioabxtrial',
            name='A',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='audioabxtrial',
            name='B',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='audioabxtrial',
            name='X',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='audioabxtrial',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audioabxtrial',
            name='key_press',
            field=models.IntegerField(null=True),
        ),
    ]
