# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0025_auto_20170201_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocattrial',
            name='new_correct',
            field=models.BooleanField(default=False),
        ),
    ]
