# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 18:51
from __future__ import unicode_literals

from django.db import migrations

def transfer_correct(apps, schema_editor):
    AudioCatTrial = apps.get_model("djreceive", "AudioCatTrial")
    
    for trial in AudioCatTrial.objects.all():
        if trial.correct == "correct":
            trial.new_correct = True
        else:
            trial.new_correct = False
        
        trial.save()

class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0026_audiocattrial_new_correct'),
    ]

    operations = [
        migrations.RunPython(transfer_correct)
    ]
