# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0027_auto_20170201_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiocattrial',
            old_name='correct',
            new_name='old_correct',
        ),
    ]
