# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0029_auto_20170201_1426'),
        ('djreceive', '0025_auto_20170201_1516'),
    ]

    operations = [
    ]
