# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djreceive', '0030_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABXTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_node_id', models.CharField(max_length=24)),
                ('trial_index', models.IntegerField()),
                ('trial_type', models.CharField(max_length=32)),
                ('time_elapsed', models.IntegerField()),
                ('timeout', models.BooleanField(default=False)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('rt', models.IntegerField()),
                ('correct', models.BooleanField(default=False)),
                ('A', models.CharField(max_length=1024, null=True)),
                ('B', models.CharField(max_length=1024, null=True)),
                ('X', models.CharField(max_length=1024, null=True)),
                ('key_press', models.IntegerField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreceive.Run')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
