# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorizationblock',
            old_name='for_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='genericsettingblock',
            old_name='for_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='similarityblock',
            old_name='for_type',
            new_name='type',
        ),
        migrations.AlterIndexTogether(
            name='categorizationblock',
            index_together=set([('global_settings_type', 'global_settings_id')]),
        ),
        migrations.AlterIndexTogether(
            name='genericsettingblock',
            index_together=set([('global_settings_type', 'global_settings_id')]),
        ),
        migrations.AlterIndexTogether(
            name='similarityblock',
            index_together=set([('global_settings_type', 'global_settings_id')]),
        ),
    ]
