# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
