# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0002_auto_20160303_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='genericsinglestimuli',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='genericstimulipair',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='microcomponentpair',
            name='setting',
        ),
        migrations.AlterIndexTogether(
            name='texttrial',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='texttrial',
            name='global_settings_type',
        ),
        migrations.RemoveField(
            model_name='texttrial',
            name='save_with',
        ),
        migrations.AlterModelOptions(
            name='categorizationblock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='similarityblock',
            options={},
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='name',
            field=models.CharField(default='block name', help_text='A short name to describe this block', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericsettingblock',
            name='name',
            field=models.CharField(default='block name', help_text='A short name to describe this block', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='name',
            field=models.CharField(default='block name', help_text='A short name to describe this block', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='genericsettingblock',
            index_together=set([]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GenericSingleStimuli',
        ),
        migrations.DeleteModel(
            name='GenericStimuliPair',
        ),
        migrations.DeleteModel(
            name='MicroComponentPair',
        ),
        migrations.DeleteModel(
            name='TextTrial',
        ),
    ]
