# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0002_auto_20160226_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroComponentPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('first', models.CharField(max_length=16)),
                ('second', models.CharField(max_length=16)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djsend.SimCatGlobalSetting')),
            ],
        ),
        migrations.AddField(
            model_name='genericsinglestimuli',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Youn can give a number to indicate the order among the pairs that point to the same block. They will be given in asceding order.', null=True),
        ),
        migrations.AddField(
            model_name='genericstimulipair',
            name='index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Youn can give a number to indicate the order among the pairs that point to the same block. They will be given in asceding order.', null=True),
        ),
    ]
