# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0002_auto_20160224_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='text_en',
            field=models.TextField(help_text='Write your instruction page here! it can even be valid html!', null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='text_es',
            field=models.TextField(help_text='Write your instruction page here! it can even be valid html!', null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='text_fr',
            field=models.TextField(help_text='Write your instruction page here! it can even be valid html!', null=True),
        ),
    ]
