# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0003_auto_20160226_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='block_type',
        ),
        migrations.AddField(
            model_name='category',
            name='setting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djsend.SimCatGlobalSetting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='microcomponentpair',
            name='index',
            field=models.PositiveIntegerField(),
        ),
    ]
