# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 18:25
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0004_auto_20160226_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here! it can even be valid html!'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text_en',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here! it can even be valid html!', null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text_es',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here! it can even be valid html!', null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text_fr',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here! it can even be valid html!', null=True),
        ),
    ]
