# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0004_auto_20160304_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='css_class',
            field=models.CharField(default='', help_text='You can set here a value for the class attribute of the <p> element that will contain the instruction.', max_length=64),
        ),
    ]
