# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0005_instruction_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizationblock',
            name='correct_text',
            field=models.CharField(default='', help_text='Text to show after a subject makes a correct categorization', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='correct_text_en',
            field=models.CharField(help_text='Text to show after a subject makes a correct categorization', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='correct_text_es',
            field=models.CharField(help_text='Text to show after a subject makes a correct categorization', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='correct_text_fr',
            field=models.CharField(help_text='Text to show after a subject makes a correct categorization', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='incorrect_text',
            field=models.CharField(default='', help_text='Text to show after a subject makes an incorrect categorization', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='incorrect_text_en',
            field=models.CharField(help_text='Text to show after a subject makes an incorrect categorization', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='incorrect_text_es',
            field=models.CharField(help_text='Text to show after a subject makes an incorrect categorization', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='incorrect_text_fr',
            field=models.CharField(help_text='Text to show after a subject makes an incorrect categorization', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='prompt',
            field=models.CharField(default='', help_text='Text to show beneath the stimuli for all trials, as a reminder of what to do.', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='prompt_en',
            field=models.CharField(help_text='Text to show beneath the stimuli for all trials, as a reminder of what to do.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='prompt_es',
            field=models.CharField(help_text='Text to show beneath the stimuli for all trials, as a reminder of what to do.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='prompt_fr',
            field=models.CharField(help_text='Text to show beneath the stimuli for all trials, as a reminder of what to do.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='timeout_message',
            field=models.CharField(default='', help_text='Text to display when a subject does not respond fast enough and the trial times out', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='timeout_message_en',
            field=models.CharField(help_text='Text to display when a subject does not respond fast enough and the trial times out', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='timeout_message_es',
            field=models.CharField(help_text='Text to display when a subject does not respond fast enough and the trial times out', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='timeout_message_fr',
            field=models.CharField(help_text='Text to display when a subject does not respond fast enough and the trial times out', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='labels',
            field=jsonfield.fields.JSONCharField(default='', help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='labels_en',
            field=jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='labels_es',
            field=jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='labels_fr',
            field=jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='prompt_en',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='prompt_es',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='prompt_fr',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='css_class',
            field=models.CharField(default='', help_text="All instructions are rendered inside an HTML 'p' element with a class attribute 'instructions'. You can add to the class attribute here.", max_length=64),
        ),
    ]
