# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0003_auto_20160224_1949'),
        ('djsend', '0005_auto_20160227_1325'),
    ]

    operations = [
    ]
