# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djsend', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='is_html',
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='save_with',
            field=models.ForeignKey(default=0, help_text="Choose the data model that will be used to save all trials that have their 'type' parameter equal to what you wrote above.     If You have different block-setting objects (like this one) that have the same 'type' but different 'save_with', then there is no guarantee which data-model will be used. This is because I think there is no real reason why two different 'categorization' blocks should be saved with different data-models: even if they have wildly different stimuli or timing settings, they should return the same kind of data.", on_delete=django.db.models.deletion.CASCADE, related_name='created_categorizationblocks', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericsettingblock',
            name='save_with',
            field=models.ForeignKey(default=0, help_text="Choose the data model that will be used to save all trials that have their 'type' parameter equal to what you wrote above.     If You have different block-setting objects (like this one) that have the same 'type' but different 'save_with', then there is no guarantee which data-model will be used. This is because I think there is no real reason why two different 'categorization' blocks should be saved with different data-models: even if they have wildly different stimuli or timing settings, they should return the same kind of data.", on_delete=django.db.models.deletion.CASCADE, related_name='created_genericsettingblocks', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='save_with',
            field=models.ForeignKey(default=0, help_text="Choose the data model that will be used to save all trials that have their 'type' parameter equal to what you wrote above.     If You have different block-setting objects (like this one) that have the same 'type' but different 'save_with', then there is no guarantee which data-model will be used. This is because I think there is no real reason why two different 'categorization' blocks should be saved with different data-models: even if they have wildly different stimuli or timing settings, they should return the same kind of data.", on_delete=django.db.models.deletion.CASCADE, related_name='created_similarityblocks', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorizationblock',
            name='global_settings_id',
            field=models.PositiveIntegerField(help_text='Which configuration object among your configs of the above type is this block attached to?'),
        ),
        migrations.AlterField(
            model_name='categorizationblock',
            name='global_settings_type',
            field=models.ForeignKey(help_text='What kind of global configuration is this object part of?', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='categorizationblock',
            name='type',
            field=models.CharField(help_text="This will be passed as the 'type' parameter to jsPsych. It tells it which plugin to use to render these trials.", max_length=26),
        ),
        migrations.AlterField(
            model_name='genericsettingblock',
            name='global_settings_id',
            field=models.PositiveIntegerField(help_text='Which configuration object among your configs of the above type is this block attached to?'),
        ),
        migrations.AlterField(
            model_name='genericsettingblock',
            name='global_settings_type',
            field=models.ForeignKey(help_text='What kind of global configuration is this object part of?', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='genericsettingblock',
            name='type',
            field=models.CharField(help_text="This will be passed as the 'type' parameter to jsPsych. It tells it which plugin to use to render these trials.", max_length=26),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here using Markdown syntax! see: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text_en',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here using Markdown syntax! see: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet', null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text_es',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here using Markdown syntax! see: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet', null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text_fr',
            field=django_markdown.models.MarkdownField(help_text='Write your instruction page here using Markdown syntax! see: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet', null=True),
        ),
        migrations.AlterField(
            model_name='similarityblock',
            name='global_settings_id',
            field=models.PositiveIntegerField(help_text='Which configuration object among your configs of the above type is this block attached to?'),
        ),
        migrations.AlterField(
            model_name='similarityblock',
            name='global_settings_type',
            field=models.ForeignKey(help_text='What kind of global configuration is this object part of?', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='similarityblock',
            name='type',
            field=models.CharField(help_text="This will be passed as the 'type' parameter to jsPsych. It tells it which plugin to use to render these trials.", max_length=26),
        ),
    ]
