# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0003_linkedstimulus_is_practice'),
        ('djsend', '0007_auto_20160306_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcatglobalsetting',
            name='microcomponent_pairs',
            field=models.ManyToManyField(to='djstim.MicroComponentPair'),
        ),
    ]
