# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0007_auto_20160228_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcatglobalsetting',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='The size of the square stimuli in pixels (length of its sides)'),
            preserve_default=False,
        ),
    ]
