# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0004_remove_microcomponentpair_setting'),
        ('djsend', '0008_simcatglobalsetting_microcomponent_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcatglobalsetting',
            name='practice_pairs',
            field=models.ManyToManyField(related_name='practice_settings', to='djstim.MicroComponentPair'),
        ),
        migrations.AlterField(
            model_name='simcatglobalsetting',
            name='microcomponent_pairs',
            field=models.ManyToManyField(related_name='settings', to='djstim.MicroComponentPair'),
        ),
    ]
