# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 03:26
from __future__ import unicode_literals

from django.db import migrations
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0008_simcatglobalsetting_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizationblock',
            name='global_settings_id',
            field=gfklookupwidget.fields.GfkLookupField(help_text='Which configuration object among your configs of the above type is this block attached to?'),
        ),
        migrations.AlterField(
            model_name='genericsettingblock',
            name='global_settings_id',
            field=gfklookupwidget.fields.GfkLookupField(help_text='Which configuration object among your configs of the above type is this block attached to?'),
        ),
        migrations.AlterField(
            model_name='similarityblock',
            name='global_settings_id',
            field=gfklookupwidget.fields.GfkLookupField(help_text='Which configuration object among your configs of the above type is this block attached to?'),
        ),
    ]
