# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0010_auto_20160405_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorizationblock',
            name='is_practice',
        ),
        migrations.RemoveField(
            model_name='genericsettingblock',
            name='is_practice',
        ),
        migrations.RemoveField(
            model_name='similarityblock',
            name='is_practice',
        ),
        migrations.AddField(
            model_name='categorizationblock',
            name='has_practice',
            field=models.BooleanField(default=False, help_text='Check if you want to mark this block to need a practice block before, useful to guide client-side JS code.'),
        ),
        migrations.AddField(
            model_name='genericsettingblock',
            name='has_practice',
            field=models.BooleanField(default=False, help_text='Check if you want to mark this block to need a practice block before, useful to guide client-side JS code.'),
        ),
        migrations.AddField(
            model_name='similarityblock',
            name='has_practice',
            field=models.BooleanField(default=False, help_text='Check if you want to mark this block to need a practice block before, useful to guide client-side JS code.'),
        ),
    ]
