# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0012_auto_20160414_2205'),
    ]

