# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0012_auto_20160414_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarityblock',
            name='timeout',
            field=models.IntegerField(default=-1, help_text='How long before trial automatically times out'),
        ),
    ]
