# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0013_auto_20160718_1118'),
        ('djsend', '0013_similarityblock_timeout'),
    ]

    operations = [
    ]
