# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0015_auto_20161102_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcedchoiceblock',
            name='prompt_en',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='forcedchoiceblock',
            name='prompt_es',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='forcedchoiceblock',
            name='prompt_fr',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options_en',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a semi-colon.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options_es',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a semi-colon.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options_fr',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a semi-colon.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_label_en',
            field=models.CharField(help_text='Question:', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_label_es',
            field=models.CharField(help_text='Question:', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_label_fr',
            field=models.CharField(help_text='Question:', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='prompt_en',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='prompt_es',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='prompt_fr',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='surveymultichoiceblock',
            name='preamble_en',
            field=models.TextField(help_text='A short paragraphe that will display at the top of your questions page', null=True),
        ),
        migrations.AddField(
            model_name='surveymultichoiceblock',
            name='preamble_es',
            field=models.TextField(help_text='A short paragraphe that will display at the top of your questions page', null=True),
        ),
        migrations.AddField(
            model_name='surveymultichoiceblock',
            name='preamble_fr',
            field=models.TextField(help_text='A short paragraphe that will display at the top of your questions page', null=True),
        ),
    ]
