# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0016_auto_20161103_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingblock',
            name='choices_en',
            field=models.CharField(blank=True, help_text='Sets the options that you can choose for the rating boxes. You have separate them with a coma and non spaces.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='choices_es',
            field=models.CharField(blank=True, help_text='Sets the options that you can choose for the rating boxes. You have separate them with a coma and non spaces.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='choices_fr',
            field=models.CharField(blank=True, help_text='Sets the options that you can choose for the rating boxes. You have separate them with a coma and non spaces.', max_length=1024, null=True),
        ),
    ]
