# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0018_auto_20161110_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedchoiceblock',
            name='prompt',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256),
        ),
        migrations.AlterField(
            model_name='forcedchoiceblock',
            name='prompt_en',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='forcedchoiceblock',
            name='prompt_es',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='forcedchoiceblock',
            name='prompt_fr',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a coma and no spaces. ex: yes,no,maybe. Leaving a space using the likert survey will put a blank in the scale. Ex: 1,,,4', max_length=1024),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options_en',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a coma and no spaces. ex: yes,no,maybe. Leaving a space using the likert survey will put a blank in the scale. Ex: 1,,,4', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options_es',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a coma and no spaces. ex: yes,no,maybe. Leaving a space using the likert survey will put a blank in the scale. Ex: 1,,,4', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_options_fr',
            field=models.CharField(help_text='Choose the labels for the possibles answers for each question. You have separate them with a coma and no spaces. ex: yes,no,maybe. Leaving a space using the likert survey will put a blank in the scale. Ex: 1,,,4', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ratingblock',
            name='prompt',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256),
        ),
        migrations.AlterField(
            model_name='ratingblock',
            name='prompt_en',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ratingblock',
            name='prompt_es',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ratingblock',
            name='prompt_fr',
            field=models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=256, null=True),
        ),
    ]
