# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0019_auto_20161111_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericglobalsetting',
            name='name',
            field=models.CharField(help_text="An identifier for this set of settings, for example 'production' or 'test settings' ", max_length=64),
        ),
        migrations.AlterField(
            model_name='simcatglobalsetting',
            name='name',
            field=models.CharField(help_text="An identifier for this set of settings, for example 'production' or 'test settings' ", max_length=64),
        ),
    ]
