# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0020_auto_20161118_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcatglobalsetting',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='If not zero, the fixed difficulty at which to run the experiment'),
        ),
    ]
