# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0021_simcatglobalsetting_difficulty'),
        ('djsend', '0022_auto_20161206_1530'),
    ]

    operations = [
    ]
