# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0023_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocatblock',
            name='key_answer',
        ),
        migrations.RemoveField(
            model_name='audiocatblock',
            name='response_ends_trial',
        ),
        migrations.AddField(
            model_name='audiocatblock',
            name='timeout_feedback',
            field=models.CharField(blank=True, help_text='Any content here will be displayed as a feedback given to the participants when he takes too long to answer the question if there is a timeout', max_length=64),
        ),
    ]
