# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djsend', '0026_auto_20161209_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSimilarityBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_settings_id', models.PositiveIntegerField(help_text='Which configuration object among your configs of the above type is this block attached to?')),
                ('name', models.CharField(help_text='A short name to describe this block', max_length=24)),
                ('position_in_timeline', models.PositiveSmallIntegerField(blank=True, help_text='This number is used by the global setting this object is part of to build its timeline. It represents the ordinal position in which this block should come.', null=True)),
                ('reprise', models.PositiveSmallIntegerField(blank=True, help_text="If set, indicates that this block is a reprise of the n'th block, where n is the value of the field", null=True)),
                ('length', models.PositiveIntegerField(blank=True, help_text="How many individual trials of this type should there be. You can leave blank if you don't need it", null=True)),
                ('type', models.CharField(help_text="This will be passed as the 'type' parameter to jsPsych. It tells it which plugin to use to render these trials.", max_length=26)),
                ('has_practice', models.BooleanField(default=False, help_text='Check if you want to mark this block to need a practice block before, useful to guide client-side JS code.')),
                ('extra_params', jsonfield.fields.JSONField(blank=True, null=True)),
                ('intervals', models.IntegerField(help_text='How many different choices are available on the slider. For example, 5 will limit the options to 5 different places on the slider')),
                ('show_ticks', models.BooleanField(help_text='If true, then the slider will have tick marks indicating where the response options lie on the slider.')),
                ('timing_first_stim', models.IntegerField(help_text='How long to play the first sound for in milliseconds.')),
                ('timing_second_stim', models.IntegerField(help_text='How long to play the second sound for in milliseconds. -1 will show the stimulus until a response is made by the subject.')),
                ('timing_post_trial', models.IntegerField(help_text='Sets the time, in milliseconds, between the current trial and the next trial.')),
                ('timeout', models.IntegerField(default=-1, help_text='time limit for the participant before the trial automatically advances')),
                ('timeout_message', models.CharField(blank=True, help_text='message to display if the participant takes too long to respond', max_length=128, null=True)),
                ('timeout_message_en', models.CharField(blank=True, help_text='message to display if the participant takes too long to respond', max_length=128, null=True)),
                ('timeout_message_fr', models.CharField(blank=True, help_text='message to display if the participant takes too long to respond', max_length=128, null=True)),
                ('timeout_message_es', models.CharField(blank=True, help_text='message to display if the participant takes too long to respond', max_length=128, null=True)),
                ('prompt', models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32)),
                ('prompt_en', models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True)),
                ('prompt_fr', models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True)),
                ('prompt_es', models.CharField(blank=True, help_text='Any content here will be displayed below the stimulus, as a reminder to the participant', max_length=32, null=True)),
                ('labels', jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64)),
                ('labels_en', jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64, null=True)),
                ('labels_fr', jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64, null=True)),
                ('labels_es', jsonfield.fields.JSONCharField(help_text='An array of tags to label the slider. must be eclosed in square brackets. Each label must be enclosed in double quotation marks. Labels must be separated by a single comma.', max_length=64, null=True)),
                ('global_settings_type', models.ForeignKey(help_text='What kind of global configuration is this object part of?', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('save_with', models.ForeignKey(help_text="Choose the data model that will be used to save all trials that have their 'type' parameter equal to what you wrote above.     If You have different block-setting objects (like this one) that have the same 'type' but different 'save_with', then there is no guarantee which data-model will be used. This is because I think there is no real reason why two different 'categorization' blocks should be saved with different data-models: even if they have wildly different stimuli or timing settings, they should return the same kind of data.", on_delete=django.db.models.deletion.CASCADE, related_name='created_audiosimilarityblocks', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterIndexTogether(
            name='audiosimilarityblock',
            index_together=set([('global_settings_type', 'global_settings_id')]),
        ),
    ]
