# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0030_auto_20170103_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorizeanimationblock',
            name='key_answer',
        ),
    ]
