# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0039_auto_20170104_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='key_forward',
            field=models.CharField(blank=True, help_text='This is the key that the subject can press in order to advance to the next page', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='show_clickable_nav',
            field=models.BooleanField(default=False, help_text='If true, then a Previous and Next button will be displayed beneath the instructions. Subjects can click the buttons to navigate.'),
        ),
    ]
