# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0042_audiocatblock_show_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosimilarityblock',
            name='timing_post_trial',
        ),
        migrations.AddField(
            model_name='audiosimilarityblock',
            name='timing_gap',
            field=models.IntegerField(blank=True, help_text='How long is the gap between the two sounds', null=True),
        ),
    ]
