# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0044_auto_20170131_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioabxblock',
            name='key_first',
            field=models.CharField(blank=True, help_text='The key that the person have to press if the first image is the same as the last', max_length=3),
        ),
        migrations.AddField(
            model_name='audioabxblock',
            name='key_second',
            field=models.CharField(blank=True, help_text='The key that the person have to press if it is the second image that is the same as the last', max_length=3),
        ),
    ]
