# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0047_auto_20170203_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcedchoiceblock',
            name='timeout',
            field=models.IntegerField(default=-1, help_text='time limit for the participant before the trial automatically advances'),
        ),
        migrations.AddField(
            model_name='forcedchoiceblock',
            name='timeout_message',
            field=models.CharField(blank=True, help_text='Any content here will be displayed as a feedback given to the participants when they time out.', max_length=128),
        ),
        migrations.AddField(
            model_name='forcedchoiceblock',
            name='timeout_message_timing',
            field=models.IntegerField(default=1000, help_text='How long to show the timeout prompt for.'),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='timeout',
            field=models.IntegerField(default=-1, help_text='time limit for the participant before the trial automatically advances'),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='timeout_message',
            field=models.CharField(blank=True, help_text='Any content here will be displayed as a feedback given to the participants when they time out.', max_length=128),
        ),
        migrations.AddField(
            model_name='ratingblock',
            name='timeout_message_timing',
            field=models.IntegerField(default=1000, help_text='How long to show the timeout prompt for.'),
        ),
    ]
