# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0049_auto_20170210_1458'),
        ('djsend', '0048_abxblock_prompt_position'),
    ]

    operations = [
    ]
