# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0050_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abxblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='animationblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='audioabxblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='audiocatblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='audiosimilarityblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='buttonresponseblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='categorizationblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='categorizeanimationblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='forcedchoiceblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='freesortblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='genericsettingblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='htmlblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='multistimmultiresponseblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ratingblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='reconstructionblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='samedifferentblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='similarityblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='singleaudioblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='singlestimblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='surveylikertblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='surveymultichoiceblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='surveytextblock',
            name='type',
        ),
        migrations.RemoveField(
            model_name='xabblock',
            name='type',
        ),
    ]
