# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0051_auto_20170215_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='abxblock',
            name='timing_fixation_cross',
            field=models.IntegerField(default=1500, help_text='How long to show the fixation cross for in milliseconds.'),
            preserve_default=False,
        ),
    ]
