# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0053_auto_20170608_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='correct',
            field=models.CharField(blank=True, help_text='what to give as a correct feedback', max_length=256),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='correct_en',
            field=models.CharField(blank=True, help_text='what to give as a correct feedback', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='correct_es',
            field=models.CharField(blank=True, help_text='what to give as a correct feedback', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='correct_fr',
            field=models.CharField(blank=True, help_text='what to give as a correct feedback', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='incorrect',
            field=models.CharField(blank=True, help_text='what to give as an incorrect feedback', max_length=256),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='incorrect_en',
            field=models.CharField(blank=True, help_text='what to give as an incorrect feedback', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='incorrect_es',
            field=models.CharField(blank=True, help_text='what to give as an incorrect feedback', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='incorrect_fr',
            field=models.CharField(blank=True, help_text='what to give as an incorrect feedback', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='is_there_feedback',
            field=models.BooleanField(default=False, help_text='If a correct/incorrect feedback will show after categorization or not'),
        ),
    ]
