# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsend', '0054_auto_20170614_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationcategorizationblock',
            name='response_wait',
            field=models.BooleanField(default=True, help_text='If the subject have to wait that the stimuli are gone before answering'),
        ),
    ]
