# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djexperiments', '0002_experiment_participations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='app_name',
        ),
        migrations.AddField(
            model_name='experiment',
            name='block_models',
            field=models.ManyToManyField(related_name='experiments', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='enforce_finish',
            field=models.BooleanField(default=False, help_text='Check this to prevent subjects from starting new participations when they already have incomplete ones pending.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='max_pending',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If subjects are allowed to have many unfinished participations, you can set the maximum here', null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='settings_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='max_repeats',
            field=models.SmallIntegerField(blank=True, help_text='If repeats are permitted, you can set a limit of repeats here.', null=True),
        ),
    ]
