# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0003_auto_20160303_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='verbose_name',
            field=models.CharField(default='my experiment', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='verbose_name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='verbose_name_es',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='verbose_name_fr',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
