# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0004_experiment_research_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='paypal_client_id',
            field=models.CharField(blank=True, help_text='If you plan on paying your subjects via Paypal, put the client id given to you when you registered your developer account. See: https://developer.paypal.com/developer/applications/', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='paypal_secret',
            field=models.CharField(blank=True, help_text='The secret key given to you by PayPal', max_length=64, null=True),
        ),
    ]
