# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0004_auto_20160303_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_markdown.models.MarkdownField(help_text="write the debrief content you'd like to show to subjects after the experiment.")),
                ('content_en', django_markdown.models.MarkdownField(help_text="write the debrief content you'd like to show to subjects after the experiment.", null=True)),
                ('content_fr', django_markdown.models.MarkdownField(help_text="write the debrief content you'd like to show to subjects after the experiment.", null=True)),
                ('content_es', django_markdown.models.MarkdownField(help_text="write the debrief content you'd like to show to subjects after the experiment.", null=True)),
            ],
        ),
    ]
