# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0007_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='paypal_client_id',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='paypal_secret',
        ),
        migrations.AddField(
            model_name='experiment',
            name='paypal_id_live',
            field=models.CharField(blank=True, help_text='Paypal client id for live authentication', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='paypal_id_sandbox',
            field=models.CharField(blank=True, help_text='Paypal client id for sandbox actions, (testing)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='paypal_secret_live',
            field=models.CharField(blank=True, help_text='Paypal secret id for live authentication', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='paypal_secret_sandbox',
            field=models.CharField(blank=True, help_text='Paypal secret for the sandbox for your application', max_length=128, null=True),
        ),
    ]
