# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0008_auto_20160722_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='paypal_id_live',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='paypal_id_sandbox',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='paypal_secret_live',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='paypal_secret_sandbox',
        ),
        migrations.AddField(
            model_name='experiment',
            name='PayPal_API_Password',
            field=models.CharField(blank=True, help_text='API Password for NVP/SOAP calls to Paypal', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='PayPal_API_Signature',
            field=models.CharField(blank=True, help_text='API Signature for NVP/SOAP calls to Paypal', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='PayPal_API_Username',
            field=models.CharField(blank=True, help_text='API username for your app to access the NVP/SOAP Paypal API', max_length=64, null=True),
        ),
    ]
