# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0011_experiment_paypal_sender_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExperiment',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('djexperiments.experiment',),
        ),
        migrations.AddField(
            model_name='experiment',
            name='total_funds_added',
            field=models.FloatField(blank=True, help_text='How much money have been added to this experiment since its creation', null=True),
        ),
    ]
