# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='participation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djcollect.Participation'),
        ),
    ]
