# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djexperiments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('parameters', jsonfield.fields.JSONField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djexperiments.Experiment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djuser.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=32, null=True)),
                ('researchs', models.ManyToManyField(blank=True, to='djexperiments.Experiment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
