# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djexperiments', '0012_auto_20160915_1520'),
        ('djuser', '0003_auto_20160304_1828'),
        ('djcollect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djexperiments.Experiment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djuser.Subject')),
            ],
        ),
    ]
