# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:42
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djcollect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='parameters',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
