# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('djstim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedStimulus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.PositiveIntegerField()),
                ('stim_id', models.PositiveIntegerField()),
                ('index', models.PositiveSmallIntegerField(blank=True, help_text='Youn can give a number to indicate the order among the pairs that point to the same block. They will be given in asceding order.', null=True)),
                ('setting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimlinks', to='contenttypes.ContentType')),
                ('stim_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocklinks', to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='genericsinglestimuli',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='genericsinglestimuli',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='genericsinglestimuli',
            name='index',
        ),
        migrations.RemoveField(
            model_name='genericstimulipair',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='genericstimulipair',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='genericstimulipair',
            name='index',
        ),
    ]
