# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0002_auto_20160323_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedstimulus',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='Check this if this stimuli should be in the practice set'),
        ),
    ]
