# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0003_linkedstimulus_is_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcomponentpair',
            name='setting',
        ),
    ]
