# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0004_remove_microcomponentpair_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttrial',
            name='is_practice',
        ),
        migrations.AddField(
            model_name='texttrial',
            name='has_practice',
            field=models.BooleanField(default=False, help_text='Check if you want to mark this block to need a practice block before, useful to guide client-side JS code.'),
        ),
    ]
