# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9 on 2016-12-02 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0006_auto_20161130_1411'),
        ('djstim', '0006_auto_20161130_1641'),
=======
# Generated by Django 1.9.1 on 2016-12-02 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0006_auto_20161130_1641'),
        ('djstim', '0006_auto_20161130_1411'),
>>>>>>> branch 'master' of https://github.com/rivasd/djPsych.git
    ]

    operations = [
    ]
