# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-02 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0006_auto_20161130_1411'),
        ('djstim', '0006_auto_20161130_1641'),
    ]

    operations = [
    ]
