# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0006_auto_20161124_1340'),
        ('djstim', '0007_merge'),
    ]

    operations = [
    ]
