# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0008_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttrial',
            name='position_in_timeline',
            field=models.PositiveSmallIntegerField(default=0, help_text='This number is used by the global setting this object is part of to build its timeline. It represents the ordinal position in which this block should come.'),
        ),
    ]
