# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstim', '0009_auto_20170131_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttrial',
            name='type',
        ),
    ]
