# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student_id',
            field=models.CharField(blank=True, help_text='If you have a student id, enter it here', max_length=12, null=True),
        ),
    ]
