# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0002_subject_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='student_participant_id',
            field=models.CharField(blank=True, help_text='If you wish to link your account with a student id so that your institution can track your participations, enter it here', max_length=12, null=True),
        ),
    ]
